name       : python-argcomplete
version    : 1.12.3
release    : 1
source     :
    - https://github.com/kislyuk/argcomplete/archive/refs/tags/v1.12.3.tar.gz : 754b516a09371e8ec98e884ea7db16d495400d4b1036d79860eb8bc1264c9680
license    : Apache-2.0
component  : programming.python
summary    : Python and tab completion, better together
description: |
    Argcomplete provides easy, extensible command line tab completion of arguments for your Python script.
build      : |
    %python3_setup
install    : |
    %python3_install
