name       : python-argcomplete
version    : 3.1.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/a/argcomplete/argcomplete-3.1.1.tar.gz : 6c4c563f14f01440aaffa3eae13441c5db2357b5eec639abe7c0b15334627dff
homepage   : https://github.com/kislyuk/argcomplete
license    : Apache-2.0
component  : programming.python
summary    : Python and tab completion, better together
description: |
    Argcomplete provides easy, extensible command line tab completion of arguments for your Python script.
builddeps  :
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
